//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 12:26:12 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lcms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.softech.vu360.lms.webservice.message.lcms.client.ArrayOfUnsignedByte;


/**
 * <p>Java class for GenerateCertificateResponse element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="GenerateCertificateResponse">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="bytes" type="{http://www.360training.com/vu360/schemas/lms/lcmsMessages}ArrayOfUnsignedByte"/>
 *         &lt;/sequence>
 *       &lt;attribute name="transactionResult" use="required" type="{http://www.360training.com/vu360/schemas/lms/lcmsMessages}TransactionResultType" />
 *       &lt;attribute name="transactionResultMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bytes"
})
@XmlRootElement(name = "GenerateCertificateResponse")
public class GenerateCertificateResponse {

    @XmlElement(namespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", required = true)
    protected ArrayOfUnsignedByte bytes;
    @XmlAttribute(required = true)
    protected TransactionResultType transactionResult;
    @XmlAttribute
    protected String transactionResultMessage;

    /**
     * Gets the value of the bytes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfUnsignedByte }
     *     
     */
    public ArrayOfUnsignedByte getBytes() {
        return bytes;
    }

    /**
     * Sets the value of the bytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfUnsignedByte }
     *     
     */
    public void setBytes(ArrayOfUnsignedByte value) {
        this.bytes = value;
    }

    /**
     * Gets the value of the transactionResult property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionResultType }
     *     
     */
    public TransactionResultType getTransactionResult() {
        return transactionResult;
    }

    /**
     * Sets the value of the transactionResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionResultType }
     *     
     */
    public void setTransactionResult(TransactionResultType value) {
        this.transactionResult = value;
    }

    /**
     * Gets the value of the transactionResultMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionResultMessage() {
        return transactionResultMessage;
    }

    /**
     * Sets the value of the transactionResultMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionResultMessage(String value) {
        this.transactionResultMessage = value;
    }

}
