//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 12:26:12 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lcms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenerateCertificateRequest element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="GenerateCertificateRequest">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="learnerEnrollmentId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "GenerateCertificateRequest")
public class GenerateCertificateRequest {

    @XmlAttribute(required = true)
    protected long learnerEnrollmentId;

    @XmlAttribute(required = true)
    protected int offset;

    @XmlAttribute(required = true)
    protected int chunkSize;

    /**
     * Gets the value of the learnerEnrollmentId property.
     * 
     */
    public long getLearnerEnrollmentId() {
        return learnerEnrollmentId;
    }

    /**
     * Sets the value of the learnerEnrollmentId property.
     * 
     */
    public void setLearnerEnrollmentId(long value) {
        this.learnerEnrollmentId = value;
    }

	/**
	 * @return the offset
	 */
	public int getOffset() {
		return offset;
	}

	/**
	 * @param offset the offset to set
	 */
	public void setOffset(int offset) {
		this.offset = offset;
	}

	/**
	 * @return the chunkSize
	 */
	public int getChunkSize() {
		return chunkSize;
	}

	/**
	 * @param chunkSize the chunkSize to set
	 */
	public void setChunkSize(int chunkSize) {
		this.chunkSize = chunkSize;
	}

    
}
