
package com.softech.vu360.lms.webservice.message.lcms;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "lmsLcmsService", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", wsdlLocation = "http://localhost:8080/lms/service/lms-lcms/lmsLcms.wsdl")
public class LmsLcmsService
    extends Service
{

    private final static URL LMSLCMSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lms/service/lms-lcms/lmsLcms.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LMSLCMSSERVICE_WSDL_LOCATION = url;
    }

    public LmsLcmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LmsLcmsService() {
        super(LMSLCMSSERVICE_WSDL_LOCATION, new QName("http://www.360training.com/vu360/schemas/lms/lcmsMessages", "lmsLcmsService"));
    }

    /**
     * 
     * @return
     *     returns LmsLcms
     */
    @WebEndpoint(name = "lmsLcmsSoap11")
    public LmsLcms getLmsLcmsSoap11() {
        return (LmsLcms)super.getPort(new QName("http://www.360training.com/vu360/schemas/lms/lcmsMessages", "lmsLcmsSoap11"), LmsLcms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LmsLcms
     */
    @WebEndpoint(name = "lmsLcmsSoap11")
    public LmsLcms getLmsLcmsSoap11(WebServiceFeature... features) {
        return (LmsLcms)super.getPort(new QName("http://www.360training.com/vu360/schemas/lms/lcmsMessages", "lmsLcmsSoap11"), LmsLcms.class, features);
    }

}
