
package com.softech.vu360.lms.webservice.message.lcms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "lmsLcms", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LmsLcms {


    /**
     * 
     * @param learnerSetupRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.lcms.LearnerSetupResponse
     */
    @WebMethod(operationName = "LearnerSetup")
    @WebResult(name = "LearnerSetupResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "LearnerSetupResponse")
    public LearnerSetupResponse learnerSetup(
        @WebParam(name = "LearnerSetupRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "LearnerSetupRequest")
        LearnerSetupRequest learnerSetupRequest);

    /**
     * 
     * @param learningSessionCompleteRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.lcms.LearningSessionCompleteResponse
     */
    @WebMethod(operationName = "LearningSessionComplete")
    @WebResult(name = "LearningSessionCompleteResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "LearningSessionCompleteResponse")
    public LearningSessionCompleteResponse learningSessionComplete(
        @WebParam(name = "LearningSessionCompleteRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "LearningSessionCompleteRequest")
        LearningSessionCompleteRequest learningSessionCompleteRequest);

    /**
     * 
     * @param updateProfileRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.lcms.UpdateProfileResponse
     */
    @WebMethod(operationName = "UpdateProfile")
    @WebResult(name = "UpdateProfileResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "UpdateProfileResponse")
    public UpdateProfileResponse updateProfile(
        @WebParam(name = "UpdateProfileRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "UpdateProfileRequest")
        UpdateProfileRequest updateProfileRequest);

    /**
     * 
     * @param publishCourseRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.lcms.PublishCourseResponse
     */
    @WebMethod(operationName = "PublishCourse")
    @WebResult(name = "PublishCourseResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "PublishCourseResponse")
    public PublishCourseResponse publishCourse(
        @WebParam(name = "PublishCourseRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/lcmsMessages", partName = "PublishCourseRequest")
        PublishCourseRequest publishCourseRequest);

}
