
package com.softech.vu360.lms.webservice.message.vcs.dfc.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "phpbbIntUserWSPortType", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhpbbIntUserWSPortType {


    /**
     * Register user to phpBB with given forum.
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.user.RegisterUserResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbUserWS.php#registerUser")
    @WebResult(name = "registerUserResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
    public RegisterUserResponse registerUser(
        @WebParam(name = "registerUser", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
        RegisterUser parameters);

    /**
     * Revoke user permissions from given forum.
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.user.RevokeUserPermissionsResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbUserWS.php#revokeUserPermissions")
    @WebResult(name = "revokeUserPermissionsResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
    public RevokeUserPermissionsResponse revokeUserPermissions(
        @WebParam(name = "revokeUserPermissions", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
        RevokeUserPermissions parameters);

    /**
     * Login user to the given forum.
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.user.LoginUserResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbUserWS.php#loginUser")
    @WebResult(name = "loginUserResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
    public LoginUserResponse loginUser(
        @WebParam(name = "loginUser", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
        LoginUser parameters);

    /**
     * Return User Avatar Name as per phpBB configurations.
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.user.GetUserAvatarNameResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbUserWS.php#getUserAvatarName")
    @WebResult(name = "getUserAvatarNameResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
    public GetUserAvatarNameResponse getUserAvatarName(
        @WebParam(name = "getUserAvatarName", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
        GetUserAvatarName parameters);

    /**
     * Save User Avatar information.
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.user.SaveUserAvatarResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbUserWS.php#saveUserAvatar")
    @WebResult(name = "saveUserAvatarResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
    public SaveUserAvatarResponse saveUserAvatar(
        @WebParam(name = "saveUserAvatar", targetNamespace = "http://www.threesixtytraining.com/phpbbIntUserWS", partName = "parameters")
        SaveUserAvatar parameters);

}
