//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.11 at 11:17:30 AM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsCourseApprovalPublish;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourseApproval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourseApproval">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="approvedCourseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseApprovalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseApprovaltype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvedCreditHours" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regulator" type="{http://www.threesixtytraining.com/LMSCourseApprovalServices.xsd}Regulator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseApproval", propOrder = {
    "approvedCourseName",
    "courseApprovalNumber",
    "courseApprovaltype",
    "approvedCreditHours",
    "regulator"
})
public class CourseApproval {

    @XmlElement(required = true)
    protected String approvedCourseName;
    @XmlElement(required = true)
    protected String courseApprovalNumber;
    @XmlElement(required = true)
    protected String courseApprovaltype;
    @XmlElement(required = true)
    protected String approvedCreditHours;
    @XmlElement(required = true)
    protected Regulator regulator;

    /**
     * Gets the value of the approvedCourseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedCourseName() {
        return approvedCourseName;
    }

    /**
     * Sets the value of the approvedCourseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedCourseName(String value) {
        this.approvedCourseName = value;
    }

    /**
     * Gets the value of the courseApprovalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseApprovalNumber() {
        return courseApprovalNumber;
    }

    /**
     * Sets the value of the courseApprovalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseApprovalNumber(String value) {
        this.courseApprovalNumber = value;
    }

    /**
     * Gets the value of the courseApprovaltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseApprovaltype() {
        return courseApprovaltype;
    }

    /**
     * Sets the value of the courseApprovaltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseApprovaltype(String value) {
        this.courseApprovaltype = value;
    }

    /**
     * Gets the value of the approvedCreditHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedCreditHours() {
        return approvedCreditHours;
    }

    /**
     * Sets the value of the approvedCreditHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedCreditHours(String value) {
        this.approvedCreditHours = value;
    }

    /**
     * Gets the value of the regulator property.
     * 
     * @return
     *     possible object is
     *     {@link Regulator }
     *     
     */
    public Regulator getRegulator() {
        return regulator;
    }

    /**
     * Sets the value of the regulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regulator }
     *     
     */
    public void setRegulator(Regulator value) {
        this.regulator = value;
    }

}
