//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.11 at 11:17:30 AM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsCourseApprovalPublish;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LMSCourseApprovalRequest element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="LMSCourseApprovalRequest">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="CourseGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CourseGroupGUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CourseApproval" type="{http://www.threesixtytraining.com/LMSCourseApprovalServices.xsd}CourseApproval"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseGuid",
    "courseGroupGUID",
    "courseApproval"
})
@XmlRootElement(name = "LMSCourseApprovalRequest")
public class LMSCourseApprovalRequest {

    @XmlElement(name = "CourseGuid", required = true)
    protected String courseGuid;
    @XmlElement(name = "CourseGroupGUID", required = true)
    protected String courseGroupGUID;
    @XmlElement(name = "CourseApproval", required = true)
    protected CourseApproval courseApproval;

    /**
     * Gets the value of the courseGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGuid() {
        return courseGuid;
    }

    /**
     * Sets the value of the courseGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGuid(String value) {
        this.courseGuid = value;
    }

    /**
     * Gets the value of the courseGroupGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGroupGUID() {
        return courseGroupGUID;
    }

    /**
     * Sets the value of the courseGroupGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGroupGUID(String value) {
        this.courseGroupGUID = value;
    }

    /**
     * Gets the value of the courseApproval property.
     * 
     * @return
     *     possible object is
     *     {@link CourseApproval }
     *     
     */
    public CourseApproval getCourseApproval() {
        return courseApproval;
    }

    /**
     * Sets the value of the courseApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseApproval }
     *     
     */
    public void setCourseApproval(CourseApproval value) {
        this.courseApproval = value;
    }

}
