package com.softech.vu360.lms.model;

import java.sql.Date;

/**
 *  ###  Generated by Oracle TopLink Workbench 11.1.1.0.0 - Thu May 28 17:00:15 GMT+06:00 2009.  ###
 */

public class RefundLineItem {

	private float amount;
	private Long id;
	private ValueHolderInterface lineItem;
	private int quantity;
	private Date refundDate;

public RefundLineItem() {
	//this.lineItem = new ValueHolder();;
}

public float getAmount() {
	return this.amount;
}

public Long getId() {
	return this.id;
}

public Integer getQuantity() {
	return this.quantity;
}

public Date getRefundDate() {
	return this.refundDate;
}

public void setAmount(float amount) {
	this.amount = amount;
}

public void setId(Long id) {
	this.id = id;
}

public void setQuantity(Integer quantity) {
	this.quantity = quantity;
}

public void setRefundDate(Date refundDate) {
	this.refundDate = refundDate;
}

/**
 * @return the LineItem
 */
public LineItem getLineItem() {
	return (LineItem)lineItem.getValue();
}

/**
 * @param LineItem
 *            the LineItem to set
 */
public void setLineItem(LineItem lineItem) {
	this.lineItem.setValue(lineItem);
}
}
