
package com.softech.vu360.lms.webservice.message.storefront.coursecatalog;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ThreeSixtyTraining-CatalogServices", targetNamespace = "http://www.threesixtytraining.com", wsdlLocation = "http://10.0.100.71/webapp/wcs/services/CatalogServices/wsdl/wsdl/ThreeSixtyTrainingService/ThreeSixtyTraining-CatalogServices.wsdl")
public class ThreeSixtyTrainingCatalogServices
    extends Service
{

    private final static URL THREESIXTYTRAININGCATALOGSERVICES_WSDL_LOCATION;
    private final static WebServiceException THREESIXTYTRAININGCATALOGSERVICES_EXCEPTION;
    private final static QName THREESIXTYTRAININGCATALOGSERVICES_QNAME = new QName("http://www.threesixtytraining.com", "ThreeSixtyTraining-CatalogServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.100.71/webapp/wcs/services/CatalogServices/wsdl/wsdl/ThreeSixtyTrainingService/ThreeSixtyTraining-CatalogServices.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        THREESIXTYTRAININGCATALOGSERVICES_WSDL_LOCATION = url;
        THREESIXTYTRAININGCATALOGSERVICES_EXCEPTION = e;
    }

    public ThreeSixtyTrainingCatalogServices() {
        super(__getWsdlLocation(), THREESIXTYTRAININGCATALOGSERVICES_QNAME);
    }

    public ThreeSixtyTrainingCatalogServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), THREESIXTYTRAININGCATALOGSERVICES_QNAME, features);
    }

    public ThreeSixtyTrainingCatalogServices(URL wsdlLocation) {
        super(wsdlLocation, THREESIXTYTRAININGCATALOGSERVICES_QNAME);
    }

    public ThreeSixtyTrainingCatalogServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, THREESIXTYTRAININGCATALOGSERVICES_QNAME, features);
    }

    public ThreeSixtyTrainingCatalogServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ThreeSixtyTrainingCatalogServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ThreeSixtyTrainingCatalogServicesPortType
     */
    @WebEndpoint(name = "CatalogServices")
    public ThreeSixtyTrainingCatalogServicesPortType getCatalogServices() {
        return super.getPort(new QName("http://www.threesixtytraining.com", "CatalogServices"), ThreeSixtyTrainingCatalogServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThreeSixtyTrainingCatalogServicesPortType
     */
    @WebEndpoint(name = "CatalogServices")
    public ThreeSixtyTrainingCatalogServicesPortType getCatalogServices(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.threesixtytraining.com", "CatalogServices"), ThreeSixtyTrainingCatalogServicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (THREESIXTYTRAININGCATALOGSERVICES_EXCEPTION!= null) {
            throw THREESIXTYTRAININGCATALOGSERVICES_EXCEPTION;
        }
        return THREESIXTYTRAININGCATALOGSERVICES_WSDL_LOCATION;
    }

}
