//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.softech.vu360.lms.webservice.message.SuggestedCourse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourseInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourseInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="courseGuidFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseGuidTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderItemURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseInfo", namespace = "http://www.example.org/SuggestedCoursesDisplayService", propOrder = {
    "courseGuidFrom",
    "courseGuidTo",
    "orderItemURL",
    "imageUrl"
})
public class CourseInfo {

    @XmlElement(required = true)
    protected String courseGuidFrom;
    @XmlElement(required = true)
    protected String courseGuidTo;
    @XmlElement(required = true)
    protected String orderItemURL;
    @XmlElement(required = true)
    protected String imageUrl;

    /**
     * Gets the value of the courseGuidFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGuidFrom() {
        return courseGuidFrom;
    }

    /**
     * Sets the value of the courseGuidFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGuidFrom(String value) {
        this.courseGuidFrom = value;
    }

    /**
     * Gets the value of the courseGuidTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGuidTo() {
        return courseGuidTo;
    }

    /**
     * Sets the value of the courseGuidTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGuidTo(String value) {
        this.courseGuidTo = value;
    }

    /**
     * Gets the value of the orderItemURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderItemURL() {
        return orderItemURL;
    }

    /**
     * Sets the value of the orderItemURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItemURL(String value) {
        this.orderItemURL = value;
    }

    /**
     * Gets the value of the imageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the value of the imageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageUrl(String value) {
        this.imageUrl = value;
    }

}
