//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.softech.vu360.lms.webservice.message.SuggestedCourse;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SuggestedCoursesDisplayService", targetNamespace = "http://www.example.org/SuggestedCoursesDisplayService/", wsdlLocation = "http://10.0.101.88/webapp/wcs/services/SuggestedCoursesDisplayService/wsdl/wsdl/ThreeSixtyTrainingService/ThreeSixtyTraining-SuggestedCoursesDisplayService.wsdl")
public class SuggestedCoursesDisplayService
    extends Service
{

    private final static URL SUGGESTEDCOURSESDISPLAYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.softech.vu360.lms.webservice.message.SuggestedCourse.SuggestedCoursesDisplayService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.softech.vu360.lms.webservice.message.SuggestedCourse.SuggestedCoursesDisplayService.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.101.88/webapp/wcs/services/SuggestedCoursesDisplayService/wsdl/wsdl/ThreeSixtyTrainingService/ThreeSixtyTraining-SuggestedCoursesDisplayService.wsdl");

        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.101.88/webapp/wcs/services/SuggestedCoursesDisplayService/wsdl/wsdl/ThreeSixtyTrainingService/ThreeSixtyTraining-SuggestedCoursesDisplayService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUGGESTEDCOURSESDISPLAYSERVICE_WSDL_LOCATION = url;
    }

    public SuggestedCoursesDisplayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuggestedCoursesDisplayService() {
        super(SUGGESTEDCOURSESDISPLAYSERVICE_WSDL_LOCATION, new QName("http://www.example.org/SuggestedCoursesDisplayService/", "SuggestedCoursesDisplayService"));
    }

    /**
     * 
     * @return
     *     returns ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType
     */
    @WebEndpoint(name = "SuggestedCoursesDisplayService")
    public ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType getSuggestedCoursesDisplayService() {
        return super.getPort(new QName("http://www.example.org/SuggestedCoursesDisplayService/", "SuggestedCoursesDisplayService"), ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType
     */
    @WebEndpoint(name = "SuggestedCoursesDisplayService")
    public ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType getSuggestedCoursesDisplayService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/SuggestedCoursesDisplayService/", "SuggestedCoursesDisplayService"), ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType.class, features);
    }

}
