//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.softech.vu360.lms.webservice.message.SuggestedCourse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuggestedCoursesDisplayResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuggestedCoursesDisplayResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseList" type="{http://www.example.org/SuggestedCoursesDisplayService}SuggestedCoursesList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuggestedCoursesDisplayResponseType", namespace = "http://www.example.org/SuggestedCoursesDisplayService", propOrder = {
    "courseList"
})
public class SuggestedCoursesDisplayResponseType {

    @XmlElement(name = "CourseList", required = true)
    protected SuggestedCoursesList courseList;

    /**
     * Gets the value of the courseList property.
     * 
     * @return
     *     possible object is
     *     {@link SuggestedCoursesList }
     *     
     */
    public SuggestedCoursesList getCourseList() {
        return courseList;
    }

    /**
     * Sets the value of the courseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuggestedCoursesList }
     *     
     */
    public void setCourseList(SuggestedCoursesList value) {
        this.courseList = value;
    }

}
