//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.softech.vu360.lms.webservice.message.SuggestedCourse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="in" type="{http://www.example.org/SuggestedCoursesDisplayService}SuggestedCoursesDisplayRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "in"
})
@XmlRootElement(name = "SuggestedCoursesDisplayRequest")
public class SuggestedCoursesDisplayRequest {

    @XmlElement(required = true)
    protected SuggestedCoursesDisplayRequestType in;

    /**
     * Gets the value of the in property.
     * 
     * @return
     *     possible object is
     *     {@link SuggestedCoursesDisplayRequestType }
     *     
     */
    public SuggestedCoursesDisplayRequestType getIn() {
        return in;
    }

    /**
     * Sets the value of the in property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuggestedCoursesDisplayRequestType }
     *     
     */
    public void setIn(SuggestedCoursesDisplayRequestType value) {
        this.in = value;
    }

}
