//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.softech.vu360.lms.webservice.message.SuggestedCourse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "ThreeSixtyTraining-SuggestedCoursesDisplayServicePortType", targetNamespace = "http://www.example.org/SuggestedCoursesDisplayService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ThreeSixtyTrainingSuggestedCoursesDisplayServicePortType {


    /**
     * 
     * @param getProductInformation
     * @return
     *     returns org.example.suggestedcoursesdisplayservice.SuggestedCoursesDisplayResponseType
     */
    @WebMethod(operationName = "GetSuggestedCourses", action = "http://www.example.org/NewOperation")
    @WebResult(name = "SuggestedCoursesDisplayResponse", targetNamespace = "http://www.example.org/SuggestedCoursesDisplayService", partName = "ShowProductInformation")
    public SuggestedCoursesDisplayResponseType getSuggestedCourses(
        @WebParam(name = "SuggestedCoursesDisplayRequest", targetNamespace = "http://www.example.org/SuggestedCoursesDisplayService", partName = "GetProductInformation")
        SuggestedCoursesDisplayRequest getProductInformation);

}
