
package com.softech.vu360.lms.webservice.message.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "lmsIntegration", targetNamespace = "http://www.360training.com/vu360/schemas/lms/integrationInterface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LmsIntegration {


    /**
     * 
     * @param batchImportLearnerRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.integration.BatchImportLearnerResponse
     */
    @WebMethod(operationName = "BatchImportLearner")
    @WebResult(name = "BatchImportLearnerResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/integrationInterface", partName = "BatchImportLearnerResponse")
    public BatchImportLearnerResponse batchImportLearner(
        @WebParam(name = "BatchImportLearnerRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/integrationInterface", partName = "BatchImportLearnerRequest")
        BatchImportLearnerRequest batchImportLearnerRequest);

}
