DROP TABLE DISTRIBUTOR CASCADE;
CREATE TABLE DISTRIBUTOR (
  ID NUMERIC(38) NOT NULL,
  BRAND_ID NUMERIC(38), 
  DISTRIBUTORGROUP_ID NUMERIC(38), 
  NAME VARCHAR NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE BRAND CASCADE;
CREATE TABLE BRAND (
  ID NUMERIC(38) NOT NULL,
  BRANDKEY VARCHAR NOT NULL, 
  NAME VARCHAR NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE LANGUAGE CASCADE;
CREATE TABLE LANGUAGE (
  ID NUMERIC(38) NOT NULL,
  COUNTRY VARCHAR, 
  LANGUAGE VARCHAR NOT NULL, 
  VARIANT VARCHAR,
  PRIMARY KEY (ID)
);

DROP TABLE LEARNER CASCADE;
CREATE TABLE LEARNER (
  ID NUMERIC(38) NOT NULL, 
  VU360USER_ID NUMERIC(38) NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE LMSADMINISTRATOR CASCADE;
CREATE TABLE LMSADMINISTRATOR (
  ID NUMERIC(38) NOT NULL,
  GLOBALADMINISTRATORTF INTEGER NOT NULL,  
  VU360USER_ID NUMERIC(38) NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE CUSTOMER CASCADE;
CREATE TABLE CUSTOMER (
  ID NUMERIC(38) NOT NULL,
  BRAND_ID NUMERIC(38), 
  NAME VARCHAR NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE VU360USER CASCADE;
CREATE TABLE VU360USER (
  ID NUMERIC(38) NOT NULL,
  ACCEPTEDEULATF INTEGER NOT NULL, 
  ACCOUNTNONEXPIREDTF INTEGER NOT NULL, 
  ACCOUNTNONLOCKEDTF INTEGER NOT NULL, 
  CHANGEPASSWORDONLOGINTF INTEGER NOT NULL, 
  CREATEDDATE TIMESTAMP NOT NULL, 
  CREDENTIALSNONEXPIREDTF INTEGER NOT NULL, 
  DOMAIN VARCHAR, 
  EMAILADDRESS VARCHAR, 
  ENABLEDTF INTEGER NOT NULL, 
  FIRSTNAME VARCHAR,
  LASTLOGONDATE TIMESTAMP, 
  LASTNAME VARCHAR, 
  LASTUPDATEDDATE TIMESTAMP, 
  NEWUSERTF INTEGER NOT NULL, 
  NUMLOGONS INTEGER NOT NULL, 
  PASSWORD VARCHAR, 
  USERNAME VARCHAR,
  PRIMARY KEY (ID) 
);

DROP TABLE TRAININGADMINISTRATOR CASCADE;
CREATE TABLE TRAININGADMINISTRATOR (
  ID NUMERIC(38) NOT NULL, 
  VU360USER_ID NUMERIC(38) NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE ORGANIZATIONALGROUP CASCADE;
CREATE TABLE ORGANIZATIONALGROUP (
  ID NUMERIC(38) NOT NULL, 
  NAME VARCHAR NOT NULL, 
  PARENTORGGROUP_ID NUMERIC(38),
  ROOTORGGROUP_ID NUMERIC(38), 
  PRIMARY KEY (ID)
);

DROP TABLE DISTRIBUTORGROUP CASCADE;
CREATE TABLE DISTRIBUTORGROUP (
  ID NUMERIC(38) NOT NULL, 
  BRAND_ID NUMERIC(38), 
  NAME VARCHAR NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE LEARNERENROLLMENT CASCADE;
CREATE TABLE ENROLLMENT (
  ID NUMERIC(38) NOT NULL,
  ENDDATE TIMESTAMP NOT NULL, 
  STARTDATE TIMESTAMP NOT NULL, 
  PRIMARY KEY (ID)
);

DROP TABLE VU360_SEQ CASCADE;
CREATE TABLE VU360_SEQ (
  NEXT_ID NUMERIC(38) NOT NULL, 
  TABLE_NAME VARCHAR NOT NULL
);

DROP TABLE COURSE CASCADE;
CREATE TABLE COURSE (
  ID NUMERIC(38) NOT NULL,
  COURSEID VARCHAR NOT NULL, 
  LANGUAGE_ID NUMERIC(38) NOT NULL, 
  COURSETITLE VARCHAR NOT NULL, 
  VERSION VARCHAR NOT NULL, 
  PRIMARY KEY (ID)
);

ALTER TABLE DISTRIBUTOR ADD CONSTRAINT DISTRIBUTOR_DISTRIBUTORGROUP FOREIGN KEY (DISTRIBUTORGROUP_ID) REFERENCES DISTRIBUTORGROUP (ID);
ALTER TABLE DISTRIBUTOR ADD CONSTRAINT DISTRIBUTOR_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID);

-- figure out why these are not working.
ALTER TABLE VU360USER ADD CONSTRAINT VU360USER_LMSADMINISTRATOR FOREIGN KEY (ID) REFERENCES LMSADMINISTRATOR (VU360USER_ID);
ALTER TABLE VU360USER ADD CONSTRAINT VU360USER_TRAININGADMINISTRATOR FOREIGN KEY (ID) REFERENCES TRAININGADMINISTRATOR (VU360USER_ID);
ALTER TABLE VU360USER ADD CONSTRAINT VU360USER_LEARNER FOREIGN KEY (ID) REFERENCES LEARNER (VU360USER_ID);
ALTER TABLE ORGANIZATIONALGROUP ADD CONSTRAINT ORGANIZATIONALGROUP_ROOTORGANIZATIONALGROUP FOREIGN KEY (ID) REFERENCES ORGANIZATIONALGROUP (ROOTORGGROUP_ID);
ALTER TABLE ORGANIZATIONALGROUP ADD CONSTRAINT ORGANIZATIONALGROUP_ORGANIZATIONALGROUP FOREIGN KEY (PARENTORGGROUP_ID) REFERENCES ORGANIZATIONALGROUP (ID);
-- end figure out why these are not working

ALTER TABLE DISTRIBUTORGROUP ADD CONSTRAINT DISTRIBUTORGROUP_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID);
ALTER TABLE COURSE ADD CONSTRAINT COURSE_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (ID);

-- seed db with data
insert into VU360USER(ID,ACCEPTEDEULATF,ACCOUNTNONEXPIREDTF,ACCOUNTNONLOCKEDTF,CHANGEPASSWORDONLOGINTF,CREATEDDATE,CREDENTIALSNONEXPIREDTF,DOMAIN,EMAILADDRESS,ENABLEDTF,FIRSTNAME,LASTLOGONDATE,LASTNAME,LASTUPDATEDDATE,NEWUSERTF,NUMLOGONS,PASSWORD,USERNAME) values(1,0,1,1,0,CURDATE(),1,NULL,'jason.burns@360training.com',1,'Jason',CURDATE(),'Burns',CURDATE(),0,0,'admin','jason');




