
/*************** RECENT COURSE BY LEARNER ID ***********/
DECLARE @LEARNERID INT
SET @LEARNERID=1

SELECT 
	[COURSE].[NAME] As CourseName, 
	[LEARNERCOURSESTATISTICS].[STATUS] As CourseProgress,
	[LEARNERCOURSESTATISTICS].[LASTACCESSDATE] As LastAccessed
FROM COURSE
LEFT OUTER JOIN LEARNERENROLLMENT ON  LEARNERENROLLMENT.COURSEID=COURSE.ID
INNER JOIN LEARNERCOURSESTATISTICS ON LEARNERCOURSESTATISTICS.LEARNERENROLLMENTID=LEARNERENROLLMENT.LEARNERENROLLMENTID
WHERE LEARNERCOURSESTATISTICS.LEARNERID= @LEARNERID
AND (LEARNERENROLLMENT.ENROLLMENTSTATUS ='ENROLLED' OR LEARNERENROLLMENT.ENROLLMENTSTATUS ='ACTIVE')
AND (LEARNERCOURSESTATISTICS.STATUS='INPROGRESS' )
Order BY [LEARNERCOURSESTATISTICS].[LASTACCESSDATE]


/************** AVAILABLE COURSE BY LEARNERID ***********/

DECLARE @LEARNERID INT
SET @LEARNERID=1

SELECT 
	[COURSE].[ID] AS CourseID,
	[COURSE].[NAME] As CourseName,
	[COURSE].[COURSETYPE] As LearningType,
	[COURSEGROUP].[NAME] AS CourseGroupName
FROM COURSE
LEFT OUTER JOIN CUSTOMERENTITLEMENT ON CUSTOMERENTITLEMENT.COURSEID=COURSE.ID
INNER JOIN  LEARNER ON LEARNER.CUSTOMER_ID=CUSTOMERENTITLEMENT.CUSTOMERID
INNER JOIN LEARNERENROLLMENT ON  LEARNERENROLLMENT.COURSEID =CUSTOMERENTITLEMENT.COURSEID
INNER JOIN COURSE_COURSEGROUP ON COURSE_COURSEGROUP.COURSEID=COURSE.ID
INNER JOIN COURSEGROUP ON COURSEGROUP.COURSEGROUPID=COURSE_COURSEGROUP.COURSEGROUPID
LEFT OUTER JOIN LEARNERCOURSESTATISTICS ON LEARNERCOURSESTATISTICS.LEARNERENROLLMENTID=LEARNERENROLLMENT.LEARNERENROLLMENTID
WHERE LEARNER.LEARNERID=@LEARNERID
AND COURSEGROUP.PARENTCOURSEGROUP_ID IS NOT NULL
UNION ALL
SELECT 
	[COURSE].[ID] AS CourseID,
	[COURSE].[NAME] As CourseName,
	[COURSE].[COURSETYPE] As LearningType,
	[COURSEGROUP].[NAME] AS CourseGroupName
FROM COURSE
LEFT OUTER JOIN CUSTOMERENTITLEMENT ON CUSTOMERENTITLEMENT.COURSEID=COURSE.ID
INNER JOIN  LEARNER ON LEARNER.CUSTOMER_ID=CUSTOMERENTITLEMENT.CUSTOMERID
INNER JOIN COURSE_COURSEGROUP ON COURSE_COURSEGROUP.COURSEID=COURSE.ID
INNER JOIN COURSEGROUP ON COURSEGROUP.COURSEGROUPID=COURSE_COURSEGROUP.COURSEGROUPID
WHERE LEARNER.LEARNERID=@LEARNERID AND CUSTOMERENTITLEMENT.COURSEID
NOT IN (SELECT COURSEID FROM LEARNERENROLLMENT WHERE LEARNERENROLLMENT.LEARNERID=@LEARNERID)
AND COURSEGROUP.PARENTCOURSEGROUP_ID IS NOT NULL
ORDER BY [COURSEGROUP].[NAME]


/************COURSE DETAIL BY LEARNER ENROLLMENT ID ********/

DECLARE @LEARNERENROLLMENTID int
SET @LEARNERENROLLMENTID=3

SELECT 
	[COURSE].[Name] As CourseName,
	LEARNERCOURSESTATISTICS.STATUS As CourseStatus,
	CAST(LEARNERCOURSESTATISTICS.PERCENTCOMPLETE AS Varchar) +'%' As PercentComplete,
	CAST(LEARNERCOURSESTATISTICS.PRETESTSCORE AS Varchar) +'%' As PreAssessmentScore,
	CAST(LEARNERCOURSESTATISTICS.AVERAGEQUIZSCORE AS Varchar) +'%' As AverageQuizeScore,
	LEARNERCOURSESTATISTICS.HEIGHESTPOSTTESTSCORE As HeighestPostAssessmentScore,
	TOTALTIMEINSECONDS As [TimeSpentInCourse(Sec.)]
FROM LEARNERCOURSESTATISTICS 
INNER JOIN LEARNERENROLLMENT ON LEARNERCOURSESTATISTICS.LEARNERENROLLMENTID=LEARNERENROLLMENT.LEARNERENROLLMENTID
INNER JOIN COURSE ON [COURSE].ID=[LEARNERENROLLMENT].[COURSEID]
WHERE LEARNERENROLLMENT.LEARNERENROLLMENTID= @LEARNERENROLLMENTID


/*************************************Couese Detail By Learner ID And Course Id*/
DECLARE @LEARNERID int
SET @LEARNERID=1
DECLARE @COURSEID int
SET @COURSEID=3 
SELECT 
	LEARNERCOURSESTATISTICS.STATUS As CourseStatus,
	CAST(LEARNERCOURSESTATISTICS.PERCENTCOMPLETE AS Varchar) +'%' As PercentComplete,
	CAST(LEARNERCOURSESTATISTICS.PRETESTSCORE AS Varchar) +'%' As PreAssessmentScore,
	CAST(LEARNERCOURSESTATISTICS.AVERAGEQUIZSCORE AS Varchar) +'%' As AverageQuizeScore,
	LEARNERCOURSESTATISTICS.HEIGHESTPOSTTESTSCORE As HeighestPostAssessmentScore,
	TOTALTIMEINSECONDS As [TimeSpentInCourse(Sec.)]
FROM LEARNERCOURSESTATISTICS 
INNER JOIN LEARNERENROLLMENT ON LEARNERCOURSESTATISTICS.LEARNERENROLLMENTID=LEARNERENROLLMENT.LEARNERENROLLMENTID
WHERE LEARNERCOURSESTATISTICS.LEARNERID= @LEARNERID
AND  LEARNERENROLLMENT.COURSEID=@COURSEID


/*********** Course Description By Course ID ************/

DECLARE @CourseId int
SET @CourseId=3

SELECT 
	[ID]   As CourseID
	,'TBD' As ApprovalNumber
	,'TBD' As RegulatingBody
	,[DELIVERYMETHOD] As DeliveryMethods
	,'TBD' As Hours
	,[SUBJECTMATTEREXPERTINFO] As SubjectMatterExpert
	,[DESCRIPTION] As CourseDescription
	,[LEARNINGOBJECTIVES] As LearningObjects
	,'TBD' As Assesments
	,[FINALEXAMINFO] As FinalExam
	,[ADDITIONALMATERIALS] As AdditionalMaterial
	,'TBD' As StateRequirments
	,[ENDOFCOURSEINSTRUCTIONS] As EndOfCourseInstruction
FROM [COURSE]
WHERE [COURSE].Id=@CourseId

