//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Course complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Course">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="courseGUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="retired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="finalExamInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="publishedonstorefront" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bussinesskey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvedcoursehours" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ceus" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Course", propOrder = {
    "id",
    "courseGUID",
    "courseStatus",
    "courseId",
    "name",
    "retired",
    "code",
    "finalExamInfo",
    "publishedonstorefront",
    "bussinesskey",
    "approvedcoursehours",
    "ceus",
    "approvalNumber"
})
public class Course {

    protected long id;
    @XmlElement(required = true)
    protected String courseGUID;
    @XmlElement(required = true)
    protected String courseStatus;
    @XmlElement(required = true)
    protected String courseId;
    @XmlElement(required = true)
    protected String name;
    protected boolean retired;
    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String finalExamInfo;
    protected boolean publishedonstorefront;
    @XmlElement(required = true)
    protected String bussinesskey;
    @XmlElement(required = true)
    protected BigDecimal approvedcoursehours;
    @XmlElement(required = true)
    protected BigDecimal ceus;
    @XmlElement(required = true)
    protected String approvalNumber;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the courseGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGUID() {
        return courseGUID;
    }

    /**
     * Sets the value of the courseGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGUID(String value) {
        this.courseGUID = value;
    }

    /**
     * Gets the value of the courseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseStatus() {
        return courseStatus;
    }

    /**
     * Sets the value of the courseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseStatus(String value) {
        this.courseStatus = value;
    }

    /**
     * Gets the value of the courseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * Sets the value of the courseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseId(String value) {
        this.courseId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the retired property.
     * 
     */
    public boolean isRetired() {
        return retired;
    }

    /**
     * Sets the value of the retired property.
     * 
     */
    public void setRetired(boolean value) {
        this.retired = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the finalExamInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalExamInfo() {
        return finalExamInfo;
    }

    /**
     * Sets the value of the finalExamInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalExamInfo(String value) {
        this.finalExamInfo = value;
    }

    /**
     * Gets the value of the publishedonstorefront property.
     * 
     */
    public boolean isPublishedonstorefront() {
        return publishedonstorefront;
    }

    /**
     * Sets the value of the publishedonstorefront property.
     * 
     */
    public void setPublishedonstorefront(boolean value) {
        this.publishedonstorefront = value;
    }

    /**
     * Gets the value of the bussinesskey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBussinesskey() {
        return bussinesskey;
    }

    /**
     * Sets the value of the bussinesskey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBussinesskey(String value) {
        this.bussinesskey = value;
    }

    /**
     * Gets the value of the approvedcoursehours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApprovedcoursehours() {
        return approvedcoursehours;
    }

    /**
     * Sets the value of the approvedcoursehours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApprovedcoursehours(BigDecimal value) {
        this.approvedcoursehours = value;
    }

    /**
     * Gets the value of the ceus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCeus() {
        return ceus;
    }

    /**
     * Sets the value of the ceus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCeus(BigDecimal value) {
        this.ceus = value;
    }

    /**
     * Gets the value of the approvalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalNumber() {
        return approvalNumber;
    }

    /**
     * Sets the value of the approvalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalNumber(String value) {
        this.approvalNumber = value;
    }

}
