//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CourseGUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CourseGroupGUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CourseApprovalRequest")
public class CourseApprovalRequest {

    @XmlAttribute(name = "CourseGUID", required = true)
    protected String courseGUID;
    @XmlAttribute(name = "CourseGroupGUID", required = true)
    protected String courseGroupGUID;

    /**
     * Gets the value of the courseGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGUID() {
        return courseGUID;
    }

    /**
     * Sets the value of the courseGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGUID(String value) {
        this.courseGUID = value;
    }

    /**
     * Gets the value of the courseGroupGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseGroupGUID() {
        return courseGroupGUID;
    }

    /**
     * Sets the value of the courseGroupGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseGroupGUID(String value) {
        this.courseGroupGUID = value;
    }

}
