//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourseApproval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourseApproval">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.360training.com/vu360/schemas/lms/sfMessages}RegulatoryApproval">
 *       &lt;sequence>
 *         &lt;element name="approvedCourseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseApprovalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseApprovaltype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvedCreditHours" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Course" type="{http://www.360training.com/vu360/schemas/lms/sfMessages}Course"/>
 *         &lt;element name="credentialCategory" type="{http://www.360training.com/vu360/schemas/lms/sfMessages}CredentialCategory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseApproval", propOrder = {
    "approvedCourseName",
    "courseApprovalNumber",
    "courseApprovaltype",
    "approvedCreditHours",
    "course",
    "credentialCategory",
    "active"
})
public class CourseApproval
    extends RegulatoryApproval
{

    @XmlElement(required = true)
    protected String approvedCourseName;
    @XmlElement(required = true)
    protected String courseApprovalNumber;
    @XmlElement(required = true)
    protected String courseApprovaltype;
    @XmlElement(required = true)
    protected BigDecimal approvedCreditHours;
    @XmlElement(name = "Course", required = true)
    protected Course course;
    protected List<CredentialCategory> credentialCategory;
    protected boolean active;

    /**
     * Gets the value of the approvedCourseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedCourseName() {
        return approvedCourseName;
    }

    /**
     * Sets the value of the approvedCourseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedCourseName(String value) {
        this.approvedCourseName = value;
    }

    /**
     * Gets the value of the courseApprovalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseApprovalNumber() {
        return courseApprovalNumber;
    }

    /**
     * Sets the value of the courseApprovalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseApprovalNumber(String value) {
        this.courseApprovalNumber = value;
    }

    /**
     * Gets the value of the courseApprovaltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseApprovaltype() {
        return courseApprovaltype;
    }

    /**
     * Sets the value of the courseApprovaltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseApprovaltype(String value) {
        this.courseApprovaltype = value;
    }

    /**
     * Gets the value of the approvedCreditHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApprovedCreditHours() {
        return approvedCreditHours;
    }

    /**
     * Sets the value of the approvedCreditHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApprovedCreditHours(BigDecimal value) {
        this.approvedCreditHours = value;
    }

    /**
     * Gets the value of the course property.
     * 
     * @return
     *     possible object is
     *     {@link Course }
     *     
     */
    public Course getCourse() {
        return course;
    }

    /**
     * Sets the value of the course property.
     * 
     * @param value
     *     allowed object is
     *     {@link Course }
     *     
     */
    public void setCourse(Course value) {
        this.course = value;
    }

    /**
     * Gets the value of the credentialCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the credentialCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCredentialCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredentialCategory }
     * 
     * 
     */
    public List<CredentialCategory> getCredentialCategory() {
        if (credentialCategory == null) {
            credentialCategory = new ArrayList<CredentialCategory>();
        }
        return this.credentialCategory;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

}
