//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Credential complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Credential">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="officialLicenseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shortLicenseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="informationLastVerifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="totalNumberOfLicense" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="otherJurisdiction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="credentialType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="renewalDeadlineType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="staggeredBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="staggeredTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="renewalFrequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hardDeadlineMonth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hardDeadlineDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hardDeadlineYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preRequisite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requirements" type="{http://www.360training.com/vu360/schemas/lms/sfMessages}CredentialCategoryRequirement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Credential", propOrder = {
    "id",
    "officialLicenseName",
    "shortLicenseName",
    "informationLastVerifiedDate",
    "totalNumberOfLicense",
    "otherJurisdiction",
    "active",
    "credentialType",
    "renewalDeadlineType",
    "staggeredBy",
    "staggeredTo",
    "renewalFrequency",
    "hardDeadlineMonth",
    "hardDeadlineDay",
    "hardDeadlineYear",
    "description",
    "preRequisite",
    "requirements"
})
public class Credential {

    protected long id;
    @XmlElement(required = true)
    protected String officialLicenseName;
    @XmlElement(required = true)
    protected String shortLicenseName;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar informationLastVerifiedDate;
    protected int totalNumberOfLicense;
    @XmlElement(required = true)
    protected String otherJurisdiction;
    protected boolean active;
    @XmlElement(required = true)
    protected String credentialType;
    @XmlElement(required = true)
    protected String renewalDeadlineType;
    @XmlElement(required = true)
    protected String staggeredBy;
    @XmlElement(required = true)
    protected String staggeredTo;
    @XmlElement(required = true)
    protected String renewalFrequency;
    @XmlElement(required = true, nillable = true)
    protected String hardDeadlineMonth;
    @XmlElement(required = true, nillable = true)
    protected String hardDeadlineDay;
    @XmlElement(required = true, nillable = true)
    protected String hardDeadlineYear;
    @XmlElement(required = true, nillable = true)
    protected String description;
    @XmlElement(required = true, nillable = true)
    protected String preRequisite;
    protected List<CredentialCategoryRequirement> requirements;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the officialLicenseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialLicenseName() {
        return officialLicenseName;
    }

    /**
     * Sets the value of the officialLicenseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialLicenseName(String value) {
        this.officialLicenseName = value;
    }

    /**
     * Gets the value of the shortLicenseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortLicenseName() {
        return shortLicenseName;
    }

    /**
     * Sets the value of the shortLicenseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortLicenseName(String value) {
        this.shortLicenseName = value;
    }

    /**
     * Gets the value of the informationLastVerifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInformationLastVerifiedDate() {
        return informationLastVerifiedDate;
    }

    /**
     * Sets the value of the informationLastVerifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInformationLastVerifiedDate(XMLGregorianCalendar value) {
        this.informationLastVerifiedDate = value;
    }

    /**
     * Gets the value of the totalNumberOfLicense property.
     * 
     */
    public int getTotalNumberOfLicense() {
        return totalNumberOfLicense;
    }

    /**
     * Sets the value of the totalNumberOfLicense property.
     * 
     */
    public void setTotalNumberOfLicense(int value) {
        this.totalNumberOfLicense = value;
    }

    /**
     * Gets the value of the otherJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherJurisdiction() {
        return otherJurisdiction;
    }

    /**
     * Sets the value of the otherJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherJurisdiction(String value) {
        this.otherJurisdiction = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the credentialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialType() {
        return credentialType;
    }

    /**
     * Sets the value of the credentialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialType(String value) {
        this.credentialType = value;
    }

    /**
     * Gets the value of the renewalDeadlineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewalDeadlineType() {
        return renewalDeadlineType;
    }

    /**
     * Sets the value of the renewalDeadlineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewalDeadlineType(String value) {
        this.renewalDeadlineType = value;
    }

    /**
     * Gets the value of the staggeredBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaggeredBy() {
        return staggeredBy;
    }

    /**
     * Sets the value of the staggeredBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaggeredBy(String value) {
        this.staggeredBy = value;
    }

    /**
     * Gets the value of the staggeredTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaggeredTo() {
        return staggeredTo;
    }

    /**
     * Sets the value of the staggeredTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaggeredTo(String value) {
        this.staggeredTo = value;
    }

    /**
     * Gets the value of the renewalFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewalFrequency() {
        return renewalFrequency;
    }

    /**
     * Sets the value of the renewalFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewalFrequency(String value) {
        this.renewalFrequency = value;
    }

    /**
     * Gets the value of the hardDeadlineMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardDeadlineMonth() {
        return hardDeadlineMonth;
    }

    /**
     * Sets the value of the hardDeadlineMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardDeadlineMonth(String value) {
        this.hardDeadlineMonth = value;
    }

    /**
     * Gets the value of the hardDeadlineDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardDeadlineDay() {
        return hardDeadlineDay;
    }

    /**
     * Sets the value of the hardDeadlineDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardDeadlineDay(String value) {
        this.hardDeadlineDay = value;
    }

    /**
     * Gets the value of the hardDeadlineYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardDeadlineYear() {
        return hardDeadlineYear;
    }

    /**
     * Sets the value of the hardDeadlineYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardDeadlineYear(String value) {
        this.hardDeadlineYear = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the preRequisite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreRequisite() {
        return preRequisite;
    }

    /**
     * Sets the value of the preRequisite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreRequisite(String value) {
        this.preRequisite = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requirements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequirements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredentialCategoryRequirement }
     * 
     * 
     */
    public List<CredentialCategoryRequirement> getRequirements() {
        if (requirements == null) {
            requirements = new ArrayList<CredentialCategoryRequirement>();
        }
        return this.requirements;
    }

}
