//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CredentialCategoryRequirement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CredentialCategoryRequirement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="numberOfHours" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="seatTimeMeasurement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reciprocity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseValidation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseApprovalPeriod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onlineCEAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="correspondenceCEAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="courseAssessments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correspondenceAllowedPreLicensing" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="correspondenceAllowedPostLicensing" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="reportingFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="CERequiresProviderApproval" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="daysToGainProviderApproval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daysToGainCourseApproval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daysToGainCourseRenewal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CredentialCategory" type="{http://www.360training.com/vu360/schemas/lms/sfMessages}CredentialCategory"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CredentialCategoryRequirement", propOrder = {
    "id",
    "numberOfHours",
    "seatTimeMeasurement",
    "reciprocity",
    "courseValidation",
    "courseApprovalPeriod",
    "onlineCEAllowed",
    "correspondenceCEAllowed",
    "courseAssessments",
    "correspondenceAllowedPreLicensing",
    "correspondenceAllowedPostLicensing",
    "reportingFees",
    "ceRequiresProviderApproval",
    "daysToGainProviderApproval",
    "daysToGainCourseApproval",
    "daysToGainCourseRenewal",
    "credentialCategory",
    "name",
    "description"
})
public class CredentialCategoryRequirement {

    protected long id;
    protected double numberOfHours;
    @XmlElement(required = true)
    protected String seatTimeMeasurement;
    @XmlElement(required = true)
    protected String reciprocity;
    @XmlElement(required = true)
    protected String courseValidation;
    @XmlElement(required = true)
    protected String courseApprovalPeriod;
    protected boolean onlineCEAllowed;
    protected boolean correspondenceCEAllowed;
    @XmlElement(required = true)
    protected String courseAssessments;
    protected boolean correspondenceAllowedPreLicensing;
    protected boolean correspondenceAllowedPostLicensing;
    @XmlElement(required = true)
    protected BigDecimal reportingFees;
    @XmlElement(name = "CERequiresProviderApproval")
    protected boolean ceRequiresProviderApproval;
    protected int daysToGainProviderApproval;
    protected int daysToGainCourseApproval;
    protected int daysToGainCourseRenewal;
    @XmlElement(name = "CredentialCategory", required = true)
    protected CredentialCategory credentialCategory;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the numberOfHours property.
     * 
     */
    public double getNumberOfHours() {
        return numberOfHours;
    }

    /**
     * Sets the value of the numberOfHours property.
     * 
     */
    public void setNumberOfHours(double value) {
        this.numberOfHours = value;
    }

    /**
     * Gets the value of the seatTimeMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatTimeMeasurement() {
        return seatTimeMeasurement;
    }

    /**
     * Sets the value of the seatTimeMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatTimeMeasurement(String value) {
        this.seatTimeMeasurement = value;
    }

    /**
     * Gets the value of the reciprocity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReciprocity() {
        return reciprocity;
    }

    /**
     * Sets the value of the reciprocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReciprocity(String value) {
        this.reciprocity = value;
    }

    /**
     * Gets the value of the courseValidation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseValidation() {
        return courseValidation;
    }

    /**
     * Sets the value of the courseValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseValidation(String value) {
        this.courseValidation = value;
    }

    /**
     * Gets the value of the courseApprovalPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseApprovalPeriod() {
        return courseApprovalPeriod;
    }

    /**
     * Sets the value of the courseApprovalPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseApprovalPeriod(String value) {
        this.courseApprovalPeriod = value;
    }

    /**
     * Gets the value of the onlineCEAllowed property.
     * 
     */
    public boolean isOnlineCEAllowed() {
        return onlineCEAllowed;
    }

    /**
     * Sets the value of the onlineCEAllowed property.
     * 
     */
    public void setOnlineCEAllowed(boolean value) {
        this.onlineCEAllowed = value;
    }

    /**
     * Gets the value of the correspondenceCEAllowed property.
     * 
     */
    public boolean isCorrespondenceCEAllowed() {
        return correspondenceCEAllowed;
    }

    /**
     * Sets the value of the correspondenceCEAllowed property.
     * 
     */
    public void setCorrespondenceCEAllowed(boolean value) {
        this.correspondenceCEAllowed = value;
    }

    /**
     * Gets the value of the courseAssessments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseAssessments() {
        return courseAssessments;
    }

    /**
     * Sets the value of the courseAssessments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseAssessments(String value) {
        this.courseAssessments = value;
    }

    /**
     * Gets the value of the correspondenceAllowedPreLicensing property.
     * 
     */
    public boolean isCorrespondenceAllowedPreLicensing() {
        return correspondenceAllowedPreLicensing;
    }

    /**
     * Sets the value of the correspondenceAllowedPreLicensing property.
     * 
     */
    public void setCorrespondenceAllowedPreLicensing(boolean value) {
        this.correspondenceAllowedPreLicensing = value;
    }

    /**
     * Gets the value of the correspondenceAllowedPostLicensing property.
     * 
     */
    public boolean isCorrespondenceAllowedPostLicensing() {
        return correspondenceAllowedPostLicensing;
    }

    /**
     * Sets the value of the correspondenceAllowedPostLicensing property.
     * 
     */
    public void setCorrespondenceAllowedPostLicensing(boolean value) {
        this.correspondenceAllowedPostLicensing = value;
    }

    /**
     * Gets the value of the reportingFees property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReportingFees() {
        return reportingFees;
    }

    /**
     * Sets the value of the reportingFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReportingFees(BigDecimal value) {
        this.reportingFees = value;
    }

    /**
     * Gets the value of the ceRequiresProviderApproval property.
     * 
     */
    public boolean isCERequiresProviderApproval() {
        return ceRequiresProviderApproval;
    }

    /**
     * Sets the value of the ceRequiresProviderApproval property.
     * 
     */
    public void setCERequiresProviderApproval(boolean value) {
        this.ceRequiresProviderApproval = value;
    }

    /**
     * Gets the value of the daysToGainProviderApproval property.
     * 
     */
    public int getDaysToGainProviderApproval() {
        return daysToGainProviderApproval;
    }

    /**
     * Sets the value of the daysToGainProviderApproval property.
     * 
     */
    public void setDaysToGainProviderApproval(int value) {
        this.daysToGainProviderApproval = value;
    }

    /**
     * Gets the value of the daysToGainCourseApproval property.
     * 
     */
    public int getDaysToGainCourseApproval() {
        return daysToGainCourseApproval;
    }

    /**
     * Sets the value of the daysToGainCourseApproval property.
     * 
     */
    public void setDaysToGainCourseApproval(int value) {
        this.daysToGainCourseApproval = value;
    }

    /**
     * Gets the value of the daysToGainCourseRenewal property.
     * 
     */
    public int getDaysToGainCourseRenewal() {
        return daysToGainCourseRenewal;
    }

    /**
     * Sets the value of the daysToGainCourseRenewal property.
     * 
     */
    public void setDaysToGainCourseRenewal(int value) {
        this.daysToGainCourseRenewal = value;
    }

    /**
     * Gets the value of the credentialCategory property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialCategory }
     *     
     */
    public CredentialCategory getCredentialCategory() {
        return credentialCategory;
    }

    /**
     * Sets the value of the credentialCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialCategory }
     *     
     */
    public void setCredentialCategory(CredentialCategory value) {
        this.credentialCategory = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
