//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.storefront.courseapproval package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.storefront.courseapproval
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CourseApprovalRequest }
     * 
     */
    public CourseApprovalRequest createCourseApprovalRequest() {
        return new CourseApprovalRequest();
    }

    /**
     * Create an instance of {@link CourseApprovalResponse }
     * 
     */
    public CourseApprovalResponse createCourseApprovalResponse() {
        return new CourseApprovalResponse();
    }

    /**
     * Create an instance of {@link CourseApproval }
     * 
     */
    public CourseApproval createCourseApproval() {
        return new CourseApproval();
    }

    /**
     * Create an instance of {@link Regulator }
     * 
     */
    public Regulator createRegulator() {
        return new Regulator();
    }

    /**
     * Create an instance of {@link RegulatoryCategory }
     * 
     */
    public RegulatoryCategory createRegulatoryCategory() {
        return new RegulatoryCategory();
    }

    /**
     * Create an instance of {@link RegulatoryApproval }
     * 
     */
    public RegulatoryApproval createRegulatoryApproval() {
        return new RegulatoryApproval();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link CredentialCategoryRequirement }
     * 
     */
    public CredentialCategoryRequirement createCredentialCategoryRequirement() {
        return new CredentialCategoryRequirement();
    }

    /**
     * Create an instance of {@link CredentialCategory }
     * 
     */
    public CredentialCategory createCredentialCategory() {
        return new CredentialCategory();
    }

}
