//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.softech.vu360.lms.webservice.message.storefront.courseapproval;
