//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 04:50:01 PM PKT 
//


package com.softech.vu360.lms.webservice.message.storefront.courseapproval;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegulatoryCategory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulatoryCategory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="regulator" type="{http://www.360training.com/vu360/schemas/lms/sfMessages}Regulator" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="categoryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="courseApprovalRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="courseApprovalPeriod" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="courseApprovalPeriodUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulatoryCategory", propOrder = {
    "id",
    "regulator",
    "categoryType",
    "courseApprovalRequired",
    "courseApprovalPeriod",
    "courseApprovalPeriodUnit"
})
public class RegulatoryCategory {

    protected long id;
    protected List<Regulator> regulator;
    @XmlElement(required = true)
    protected String categoryType;
    protected boolean courseApprovalRequired;
    protected double courseApprovalPeriod;
    @XmlElement(required = true)
    protected String courseApprovalPeriodUnit;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the regulator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regulator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegulator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Regulator }
     * 
     * 
     */
    public List<Regulator> getRegulator() {
        if (regulator == null) {
            regulator = new ArrayList<Regulator>();
        }
        return this.regulator;
    }

    /**
     * Gets the value of the categoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryType() {
        return categoryType;
    }

    /**
     * Sets the value of the categoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryType(String value) {
        this.categoryType = value;
    }

    /**
     * Gets the value of the courseApprovalRequired property.
     * 
     */
    public boolean isCourseApprovalRequired() {
        return courseApprovalRequired;
    }

    /**
     * Sets the value of the courseApprovalRequired property.
     * 
     */
    public void setCourseApprovalRequired(boolean value) {
        this.courseApprovalRequired = value;
    }

    /**
     * Gets the value of the courseApprovalPeriod property.
     * 
     */
    public double getCourseApprovalPeriod() {
        return courseApprovalPeriod;
    }

    /**
     * Sets the value of the courseApprovalPeriod property.
     * 
     */
    public void setCourseApprovalPeriod(double value) {
        this.courseApprovalPeriod = value;
    }

    /**
     * Gets the value of the courseApprovalPeriodUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseApprovalPeriodUnit() {
        return courseApprovalPeriodUnit;
    }

    /**
     * Sets the value of the courseApprovalPeriodUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseApprovalPeriodUnit(String value) {
        this.courseApprovalPeriodUnit = value;
    }

}
