package com.softech.vu360.util;

public enum CustomFieldEntityType {
	CUSTOMFIELD_ALL,
	CUSTOMFIELD_CONTACT,
	CUSTOMFIELD_REGULATOR,
	CUSTOMFIELD_REGULATOR_CATEGORY,
	CUSTOMFIELD_CREDENTIAL,
	CUSTOMFIELD_CREDENTIALREQUIREMENT,
	CUSTOMFIELD_PROVIDER,
	CUSTOMFIELD_INSTRUCTOR,
	CUSTOMFIELD_COURSEAPPROVAL,
	CUSTOMFIELD_PROVIDERAPPROVAL,
	CUSTOMFIELD_INSTRUCTORAPPROVAL,
	CUSTOMFIELD_CREDENTIALCATEGORY;
}
