//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:43:11 PM CST 
//


package com.softech.vu360.lms.webservice.message.storefront.synccustomer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.softech.vu360.lms.webservice.message.storefront.client.CustomerData;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StoreID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuthenticationCredential" type="{http://www.threesixtytraining.com/SyncCustomerServices.xsd}UpdateUserAuthenticationCredential"/>
 *         &lt;element name="Customer" type="{http://www.threesixtytraining.com/SyncCustomerServices.xsd}CustomerData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionID",
    "storeID",
    "authenticationCredential",
    "customer"
})
@XmlRootElement(name = "GetSyncCustomerRequest")
public class GetSyncCustomerRequest {

    @XmlElement(name = "TransactionID", required = true)
    protected String transactionID;
    @XmlElement(name = "StoreID", required = true)
    protected String storeID;
    @XmlElement(name = "AuthenticationCredential", required = true)
    protected UpdateUserAuthenticationCredential authenticationCredential;
    @XmlElement(name = "Customer", required = true)
    protected com.softech.vu360.lms.webservice.message.storefront.synccustomer.CustomerData customer;

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the storeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreID() {
        return storeID;
    }

    /**
     * Sets the value of the storeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreID(String value) {
        this.storeID = value;
    }

    /**
     * Gets the value of the authenticationCredential property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateUserAuthenticationCredential }
     *     
     */
    public UpdateUserAuthenticationCredential getAuthenticationCredential() {
        return authenticationCredential;
    }

    /**
     * Sets the value of the authenticationCredential property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateUserAuthenticationCredential }
     *     
     */
    public void setAuthenticationCredential(UpdateUserAuthenticationCredential value) {
        this.authenticationCredential = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerData }
     *     
     */
    public com.softech.vu360.lms.webservice.message.storefront.synccustomer.CustomerData getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerData }
     *     
     */
    public void setCustomer(com.softech.vu360.lms.webservice.message.storefront.synccustomer.CustomerData value) {
        this.customer = value;
    }

}
