//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:43:11 PM CST 
//


package com.softech.vu360.lms.webservice.message.storefront.synccustomer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.storefront package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.storefront
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSyncCustomerRequest }
     * 
     */
    public GetSyncCustomerRequest createGetSyncCustomerRequest() {
        return new GetSyncCustomerRequest();
    }

    /**
     * Create an instance of {@link UpdateUserAuthenticationCredential }
     * 
     */
    public UpdateUserAuthenticationCredential createUpdateUserAuthenticationCredential() {
        return new UpdateUserAuthenticationCredential();
    }

    /**
     * Create an instance of {@link ShowSyncCustomerResponse }
     * 
     */
    public ShowSyncCustomerResponse createShowSyncCustomerResponse() {
        return new ShowSyncCustomerResponse();
    }

    /**
     * Create an instance of {@link CustomerData }
     * 
     */
    public CustomerData createCustomerData() {
        return new CustomerData();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

}
