//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:43:11 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.threesixtytraining.com/SyncCustomerServices.xsd")
package com.softech.vu360.lms.webservice.message.storefront.synccustomer;
