
package com.softech.vu360.lms.webservice.message.vcs.dfc.forum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "phpbbIntForumWSPortType", targetNamespace = "http://www.threesixtytraining.com/phpbbIntForumWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhpbbIntForumWSPortType {


    /**
     * Create Forum under specified Category
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.forum.CreateForumResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbForumWS.php#createForum")
    @WebResult(name = "createForumResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntForumWS", partName = "parameters")
    public CreateForumResponse createForum(
        @WebParam(name = "createForum", targetNamespace = "http://www.threesixtytraining.com/phpbbIntForumWS", partName = "parameters")
        CreateForum parameters);

    /**
     * Delete Forum and its related information
     * 
     * @param parameters
     * @return
     *     returns com.softech.vu360.lms.webservice.message.vcs.dfc.forum.DeleteForumResponse
     */
    @WebMethod(action = "http://localhost/phpbbIntegrationService/service/phpbbForumWS.php#deleteForum")
    @WebResult(name = "deleteForumResponse", targetNamespace = "http://www.threesixtytraining.com/phpbbIntForumWS", partName = "parameters")
    public DeleteForumResponse deleteForum(
        @WebParam(name = "deleteForum", targetNamespace = "http://www.threesixtytraining.com/phpbbIntForumWS", partName = "parameters")
        DeleteForum parameters);

}
