
package com.softech.vu360.lms.webservice.message.vcs.dfc.forum;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "phpbbIntForumWS", targetNamespace = "http://www.threesixtytraining.com/phpbbIntForumWS", wsdlLocation = "http://localhost/phpbbIntegrationService/service/phpbbForumWS.php?wsdl")
public class PhpbbIntForumWS
    extends Service
{

    private final static URL PHPBBINTFORUMWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.softech.vu360.lms.webservice.message.vcs.dfc.forum.PhpbbIntForumWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.softech.vu360.lms.webservice.message.vcs.dfc.forum.PhpbbIntForumWS.class.getResource(".");
            url = new URL(baseUrl, "http://localhost/phpbbIntegrationService/service/phpbbForumWS.php?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/phpbbIntegrationService/service/phpbbForumWS.php?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PHPBBINTFORUMWS_WSDL_LOCATION = url;
    }

    public PhpbbIntForumWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhpbbIntForumWS() {
        super(PHPBBINTFORUMWS_WSDL_LOCATION, new QName("http://www.threesixtytraining.com/phpbbIntForumWS", "phpbbIntForumWS"));
    }

    /**
     * 
     * @return
     *     returns PhpbbIntForumWSPortType
     */
    @WebEndpoint(name = "phpbbIntForumWSPort")
    public PhpbbIntForumWSPortType getPhpbbIntForumWSPort() {
        return super.getPort(new QName("http://www.threesixtytraining.com/phpbbIntForumWS", "phpbbIntForumWSPort"), PhpbbIntForumWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhpbbIntForumWSPortType
     */
    @WebEndpoint(name = "phpbbIntForumWSPort")
    public PhpbbIntForumWSPortType getPhpbbIntForumWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.threesixtytraining.com/phpbbIntForumWS", "phpbbIntForumWSPort"), PhpbbIntForumWSPortType.class, features);
    }

}
