//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.21 at 12:07:11 PM PKT 
//


package com.softech.vu360.lms.webservice.message.predict360;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.predict360 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.predict360
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SurveyFrameworkSoapVO }
     * 
     */
    public SurveyFrameworkSoapVO createSurveyFrameworkSoapVO() {
        return new SurveyFrameworkSoapVO();
    }

    /**
     * Create an instance of {@link SurveyQuestionSoapVO }
     * 
     */
    public SurveyQuestionSoapVO createSurveyQuestionSoapVO() {
        return new SurveyQuestionSoapVO();
    }

    /**
     * Create an instance of {@link SurveyImportPredictRequest }
     * 
     */
    public SurveyImportPredictRequest createSurveyImportPredictRequest() {
        return new SurveyImportPredictRequest();
    }

    /**
     * Create an instance of {@link SurveySectionSoapVO }
     * 
     */
    public SurveySectionSoapVO createSurveySectionSoapVO() {
        return new SurveySectionSoapVO();
    }

    /**
     * Create an instance of {@link SurveyQuestionAnswerSoapVO }
     * 
     */
    public SurveyQuestionAnswerSoapVO createSurveyQuestionAnswerSoapVO() {
        return new SurveyQuestionAnswerSoapVO();
    }

    /**
     * Create an instance of {@link SurveyImportPredictResponse }
     * 
     */
    public SurveyImportPredictResponse createSurveyImportPredictResponse() {
        return new SurveyImportPredictResponse();
    }

}
