//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.21 at 12:07:11 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.360training.com/vu360/schemas/lms/surveyimport", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.softech.vu360.lms.webservice.message.predict360;
