
package com.softech.vu360.lms.webservice.message.storefront;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "lmsStorefront", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LmsStorefront {


    /**
     * 
     * @param orderCreatedRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.storefront.OrderCreatedResponse
     */
    @WebMethod(operationName = "OrderCreated")
    @WebResult(name = "OrderCreatedResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "OrderCreatedResponse")
    public OrderCreatedResponse orderCreated(
        @WebParam(name = "OrderCreatedRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "OrderCreatedRequest")
        OrderCreatedRequest orderCreatedRequest);

    /**
     * 
     * @param courseDetailsRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.storefront.CourseDetailsResponse
     */
    @WebMethod(operationName = "CourseDetails")
    @WebResult(name = "CourseDetailsResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "CourseDetailsResponse")
    public CourseDetailsResponse courseDetails(
        @WebParam(name = "CourseDetailsRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "CourseDetailsRequest")
        CourseDetailsRequest courseDetailsRequest);

    /**
     * 
     * @param refundRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.storefront.RefundResponse
     */
    @WebMethod(operationName = "Refund")
    @WebResult(name = "RefundResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "RefundResponse")
    public RefundResponse refund(
        @WebParam(name = "RefundRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "RefundRequest")
        RefundRequest refundRequest);

    /**
     * 
     * @param updateProfileRequest
     * @return
     *     returns com.softech.vu360.lms.webservice.message.storefront.UpdateProfileResponse
     */
    @WebMethod(operationName = "UpdateProfile")
    @WebResult(name = "UpdateProfileResponse", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "UpdateProfileResponse")
    public UpdateProfileResponse updateProfile(
        @WebParam(name = "UpdateProfileRequest", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", partName = "UpdateProfileRequest")
        UpdateProfileRequest updateProfileRequest);

}
