
package com.softech.vu360.lms.webservice.message.storefront;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "lmsStorefrontService", targetNamespace = "http://www.360training.com/vu360/schemas/lms/sfMessages", wsdlLocation = "http://localhost:8080/lms/service/lmsStorefront.wsdl")
public class LmsStorefrontService
    extends Service
{

    private final static URL LMSSTOREFRONTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lms/service/lmsStorefront.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LMSSTOREFRONTSERVICE_WSDL_LOCATION = url;
    }

    public LmsStorefrontService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LmsStorefrontService() {
        super(LMSSTOREFRONTSERVICE_WSDL_LOCATION, new QName("http://www.360training.com/vu360/schemas/lms/sfMessages", "lmsStorefrontService"));
    }

    /**
     * 
     * @return
     *     returns LmsStorefront
     */
    @WebEndpoint(name = "lmsStorefrontSoap11")
    public LmsStorefront getLmsStorefrontSoap11() {
        return (LmsStorefront)super.getPort(new QName("http://www.360training.com/vu360/schemas/lms/sfMessages", "lmsStorefrontSoap11"), LmsStorefront.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LmsStorefront
     */
    @WebEndpoint(name = "lmsStorefrontSoap11")
    public LmsStorefront getLmsStorefrontSoap11(WebServiceFeature... features) {
        return (LmsStorefront)super.getPort(new QName("http://www.360training.com/vu360/schemas/lms/sfMessages", "lmsStorefrontSoap11"), LmsStorefront.class, features);
    }

}
