//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 05:15:03 PM PKT 
//


package com.softech.vu360.lms.webservice.message.predict360.survey;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="totalAssignedSurvey" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="inprogressSurvey" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="completedSurvey" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="overdueSurvey" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "UserAssignedSurveysStatisticsResponse")
public class UserAssignedSurveysStatisticsResponse {

    @XmlAttribute(name = "totalAssignedSurvey", required = true)
    protected int totalAssignedSurvey;
    @XmlAttribute(name = "inprogressSurvey")
    protected Integer inprogressSurvey;
    @XmlAttribute(name = "completedSurvey")
    protected Integer completedSurvey;
    @XmlAttribute(name = "overdueSurvey")
    protected Integer overdueSurvey;
    @XmlAttribute(name = "username")
    protected String username;

    /**
     * Gets the value of the totalAssignedSurvey property.
     * 
     */
    public int getTotalAssignedSurvey() {
        return totalAssignedSurvey;
    }

    /**
     * Sets the value of the totalAssignedSurvey property.
     * 
     */
    public void setTotalAssignedSurvey(int value) {
        this.totalAssignedSurvey = value;
    }

    /**
     * Gets the value of the inprogressSurvey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInprogressSurvey() {
        return inprogressSurvey;
    }

    /**
     * Sets the value of the inprogressSurvey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInprogressSurvey(Integer value) {
        this.inprogressSurvey = value;
    }

    /**
     * Gets the value of the completedSurvey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompletedSurvey() {
        return completedSurvey;
    }

    /**
     * Sets the value of the completedSurvey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompletedSurvey(Integer value) {
        this.completedSurvey = value;
    }

    /**
     * Gets the value of the overdueSurvey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverdueSurvey() {
        return overdueSurvey;
    }

    /**
     * Sets the value of the overdueSurvey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverdueSurvey(Integer value) {
        this.overdueSurvey = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

}
