//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 07:58:34 PM PKT 
//


package com.softech.vu360.lms.webservice.message.predict360.trainingplan;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trainingPlanAssignments" type="{http://www.360training.com/vu360/schemas/lms/trainingplans}TrainingPlanAssignmentSoapVO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trainingPlanAssignments"
})
@XmlRootElement(name = "GetTrainingPlanAssignmentsByDateResponse")
public class GetTrainingPlanAssignmentsByDateResponse {

    @XmlElement(nillable = true)
    protected List<TrainingPlanAssignmentSoapVO> trainingPlanAssignments;

    /**
     * Gets the value of the trainingPlanAssignments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainingPlanAssignments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainingPlanAssignments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainingPlanAssignmentSoapVO }
     * 
     * 
     */
    public List<TrainingPlanAssignmentSoapVO> getTrainingPlanAssignments() {
        if (trainingPlanAssignments == null) {
            trainingPlanAssignments = new ArrayList<TrainingPlanAssignmentSoapVO>();
        }
        return this.trainingPlanAssignments;
    }
    
    public void setTrainingPlanAssignments(List<TrainingPlanAssignmentSoapVO> trainingPlanAssignments) {
        this.trainingPlanAssignments = trainingPlanAssignments;
    }

}
