//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 10:37:42 AM PKT 
//


package com.softech.vu360.lms.webservice.message.predict360.trainingplan;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trainingplancourses" type="{http://www.360training.com/vu360/schemas/lms/trainingplans}TrainingPlanCourseSoapVO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trainingplancourses"
})
@XmlRootElement(name = "GetTrainingPlanCoursesByDueDateResponse")
public class GetTrainingPlanCoursesByDueDateResponse {

    @XmlElement(nillable = true)
    protected List<TrainingPlanCourseSoapVO> trainingplancourses;

    /**
     * Gets the value of the trainingplancourses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainingplancourses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainingplancourses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainingPlanCourseSoapVO }
     * 
     * 
     */
    public List<TrainingPlanCourseSoapVO> getTrainingplancourses() {
        if (trainingplancourses == null) {
            trainingplancourses = new ArrayList<TrainingPlanCourseSoapVO>();
        }
        return this.trainingplancourses;
    }

}
