//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 07:58:34 PM PKT 
//


package com.softech.vu360.lms.webservice.message.predict360.trainingplan;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.predict360.trainingplan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.predict360.trainingplan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEmployeeCoursesStatusRequest }
     * 
     */
    public GetEmployeeCoursesStatusRequest createGetEmployeeCoursesStatusRequest() {
        return new GetEmployeeCoursesStatusRequest();
    }

    /**
     * Create an instance of {@link GetEmployeeCoursesStatusResponse }
     * 
     */
    public GetEmployeeCoursesStatusResponse createGetEmployeeCoursesStatusResponse() {
        return new GetEmployeeCoursesStatusResponse();
    }

    /**
     * Create an instance of {@link TrainingPlanCourseStatusSoapVO }
     * 
     */
    public TrainingPlanCourseStatusSoapVO createTrainingPlanCourseStatusSoapVO() {
        return new TrainingPlanCourseStatusSoapVO();
    }

    /**
     * Create an instance of {@link GetTrainingPlanCoursesByDueDateRequest }
     * 
     */
    public GetTrainingPlanCoursesByDueDateRequest createGetTrainingPlanCoursesByDueDateRequest() {
        return new GetTrainingPlanCoursesByDueDateRequest();
    }

    /**
     * Create an instance of {@link TrainingPlanPredictRequest }
     * 
     */
    public TrainingPlanPredictRequest createTrainingPlanPredictRequest() {
        return new TrainingPlanPredictRequest();
    }

    /**
     * Create an instance of {@link TrainingPlanPredictResponse }
     * 
     */
    public TrainingPlanPredictResponse createTrainingPlanPredictResponse() {
        return new TrainingPlanPredictResponse();
    }

    /**
     * Create an instance of {@link TrainingPlanSoapVO }
     * 
     */
    public TrainingPlanSoapVO createTrainingPlanSoapVO() {
        return new TrainingPlanSoapVO();
    }

    /**
     * Create an instance of {@link GetTrainingPlanAssignmentsByDateRequest }
     * 
     */
    public GetTrainingPlanAssignmentsByDateRequest createGetTrainingPlanAssignmentsByDateRequest() {
        return new GetTrainingPlanAssignmentsByDateRequest();
    }

    /**
     * Create an instance of {@link GetAllTraingPlansByIdsResponse }
     * 
     */
    public GetAllTraingPlansByIdsResponse createGetAllTraingPlansByIdsResponse() {
        return new GetAllTraingPlansByIdsResponse();
    }

    /**
     * Create an instance of {@link GetTrainingPlanAssignmentsByDateResponse }
     * 
     */
    public GetTrainingPlanAssignmentsByDateResponse createGetTrainingPlanAssignmentsByDateResponse() {
        return new GetTrainingPlanAssignmentsByDateResponse();
    }

    /**
     * Create an instance of {@link TrainingPlanAssignmentSoapVO }
     * 
     */
    public TrainingPlanAssignmentSoapVO createTrainingPlanAssignmentSoapVO() {
        return new TrainingPlanAssignmentSoapVO();
    }

    /**
     * Create an instance of {@link GetAllTraingPlansByIdsRequest }
     * 
     */
    public GetAllTraingPlansByIdsRequest createGetAllTraingPlansByIdsRequest() {
        return new GetAllTraingPlansByIdsRequest();
    }

    /**
     * Create an instance of {@link GetTrainingPlanCoursesByDueDateResponse }
     * 
     */
    public GetTrainingPlanCoursesByDueDateResponse createGetTrainingPlanCoursesByDueDateResponse() {
        return new GetTrainingPlanCoursesByDueDateResponse();
    }

    /**
     * Create an instance of {@link TrainingPlanCourseSoapVO }
     * 
     */
    public TrainingPlanCourseSoapVO createTrainingPlanCourseSoapVO() {
        return new TrainingPlanCourseSoapVO();
    }

}
