//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 07:58:34 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.360training.com/vu360/schemas/lms/trainingplans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.softech.vu360.lms.webservice.message.predict360.trainingplan;
