//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 01:57:12 PM PKT 
//


package com.softech.vu360.lms.webservice.message.predict360.trainingplan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrainingPlanCourseStatusSoapVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainingPlanCourseStatusSoapVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="userName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="email" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="expiredCourses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="completedCourses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="inProgressCourses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="notStartedCourses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainingPlanCourseStatusSoapVO")
public class TrainingPlanCourseStatusSoapVO {

    @XmlAttribute(name = "userName")
    protected String userName;
    @XmlAttribute(name = "email")
    protected String email;
    @XmlAttribute(name = "expiredCourses")
    protected Integer expiredCourses;
    @XmlAttribute(name = "completedCourses")
    protected Integer completedCourses;
    @XmlAttribute(name = "inProgressCourses")
    protected Integer inProgressCourses;
    @XmlAttribute(name = "notStartedCourses")
    protected Integer notStartedCourses;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the expiredCourses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpiredCourses() {
        return expiredCourses;
    }

    /**
     * Sets the value of the expiredCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpiredCourses(Integer value) {
        this.expiredCourses = value;
    }

    /**
     * Gets the value of the completedCourses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompletedCourses() {
        return completedCourses;
    }

    /**
     * Sets the value of the completedCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompletedCourses(Integer value) {
        this.completedCourses = value;
    }

    /**
     * Gets the value of the inProgressCourses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInProgressCourses() {
        return inProgressCourses;
    }

    /**
     * Sets the value of the inProgressCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInProgressCourses(Integer value) {
        this.inProgressCourses = value;
    }

    /**
     * Gets the value of the notStartedCourses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNotStartedCourses() {
        return notStartedCourses;
    }

    /**
     * Sets the value of the notStartedCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNotStartedCourses(Integer value) {
        this.notStartedCourses = value;
    }

}
