//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 01:32:52 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/softech/vu360/lms/selfservice/webservices/orderservice")
package com.softech.vu360.lms.webservice.message.selfservice;
