
package com.softech.vu360.lms.webservice.message.lcms.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.softech.vu360.lms.webservice.message.lcms.ArrayOfLong;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LMSServicesSoap", targetNamespace = "http://360training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LMSServicesSoap {


    /**
     * 
     * @param buffer
     * @param fileName
     * @param offset
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UploadAssetInChunk", action = "http://360training.com/UploadAssetInChunk")
    @WebResult(name = "UploadAssetInChunkResult", targetNamespace = "http://360training.com/")
    @RequestWrapper(localName = "UploadAssetInChunk", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.UploadAssetInChunk")
    @ResponseWrapper(localName = "UploadAssetInChunkResponse", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.UploadAssetInChunkResponse")
    public boolean uploadAssetInChunk(
        @WebParam(name = "fileName", targetNamespace = "http://360training.com/")
        String fileName,
        @WebParam(name = "buffer", targetNamespace = "http://360training.com/")
        ArrayOfUnsignedByte buffer,
        @WebParam(name = "Offset", targetNamespace = "http://360training.com/")
        long offset);

    /**
     * 
     * @param content
     * @param keywords
     * @param assetId
     * @param assetType
     * @param description
     * @param contentOwnerId
     * @param name
     * @param fileName
     * @param loggedInUserID
     * @param itemsPerPage
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SaveAsset", action = "http://360training.com/SaveAsset")
    @WebResult(name = "SaveAssetResult", targetNamespace = "http://360training.com/")
    @RequestWrapper(localName = "SaveAsset", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.SaveAsset")
    @ResponseWrapper(localName = "SaveAssetResponse", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.SaveAssetResponse")
    public int saveAsset(
        @WebParam(name = "assetType", targetNamespace = "http://360training.com/")
        String assetType,
        @WebParam(name = "assetId", targetNamespace = "http://360training.com/")
        long assetId,
        @WebParam(name = "name", targetNamespace = "http://360training.com/")
        String name,
        @WebParam(name = "description", targetNamespace = "http://360training.com/")
        String description,
        @WebParam(name = "keywords", targetNamespace = "http://360training.com/")
        String keywords,
        @WebParam(name = "fileName", targetNamespace = "http://360training.com/")
        String fileName,
        @WebParam(name = "itemsPerPage", targetNamespace = "http://360training.com/")
        int itemsPerPage,
        @WebParam(name = "content", targetNamespace = "http://360training.com/")
        String content,
        @WebParam(name = "contentOwnerId", targetNamespace = "http://360training.com/")
        int contentOwnerId,
        @WebParam(name = "loggedInUserID", targetNamespace = "http://360training.com/")
        int loggedInUserID);

    /**
     * 
     * @param assetIds
     * @param active
     * @param loggedInUserID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdateAssetStatus", action = "http://360training.com/UpdateAssetStatus")
    @WebResult(name = "UpdateAssetStatusResult", targetNamespace = "http://360training.com/")
    @RequestWrapper(localName = "UpdateAssetStatus", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.UpdateAssetStatus")
    @ResponseWrapper(localName = "UpdateAssetStatusResponse", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.UpdateAssetStatusResponse")
    public int updateAssetStatus(
        @WebParam(name = "assetIds", targetNamespace = "http://360training.com/")
        ArrayOfLong assetIds,
        @WebParam(name = "active", targetNamespace = "http://360training.com/")
        boolean active,
        @WebParam(name = "loggedInUserID", targetNamespace = "http://360training.com/")
        int loggedInUserID);

    /**
     * 
     * @param bufferSize
     * @param filePath
     * @param offset
     * @return
     *     returns com.softech.vu360.lms.webservice.message.lcms.client.ArrayOfUnsignedByte
     */
    @WebMethod(operationName = "DownloadAssetInChunk", action = "http://360training.com/DownloadAssetInChunk")
    @WebResult(name = "DownloadAssetInChunkResult", targetNamespace = "http://360training.com/")
    @RequestWrapper(localName = "DownloadAssetInChunk", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.DownloadAssetInChunk")
    @ResponseWrapper(localName = "DownloadAssetInChunkResponse", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.DownloadAssetInChunkResponse")
    public ArrayOfUnsignedByte downloadAssetInChunk(
        @WebParam(name = "filePath", targetNamespace = "http://360training.com/")
        String filePath,
        @WebParam(name = "offset", targetNamespace = "http://360training.com/")
        long offset,
        @WebParam(name = "bufferSize", targetNamespace = "http://360training.com/")
        int bufferSize);

    /**
     * 
     * @param assetId
     * @return
     *     returns com.softech.vu360.lms.webservice.message.lcms.client.ArrayOfString
     */
    @WebMethod(operationName = "GetAssetFileInfo", action = "http://360training.com/GetAssetFileInfo")
    @WebResult(name = "GetAssetFileInfoResult", targetNamespace = "http://360training.com/")
    @RequestWrapper(localName = "GetAssetFileInfo", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.GetAssetFileInfo")
    @ResponseWrapper(localName = "GetAssetFileInfoResponse", targetNamespace = "http://360training.com/", className = "com.softech.vu360.lms.webservice.message.lcms.client.GetAssetFileInfoResponse")
    public ArrayOfString getAssetFileInfo(
        @WebParam(name = "assetId", targetNamespace = "http://360training.com/")
        long assetId);

}
