
package com.softech.vu360.lms.webservice.message.lcms.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LMSServices", targetNamespace = "http://360training.com/", wsdlLocation = "http://10.0.100.250/LCMSServer/LMSWebService/LMSServices.asmx?WSDL")
public class LMSServices
    extends Service
{

    private final static URL LMSSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.softech.vu360.lms.webservice.message.lcms.client.LMSServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.softech.vu360.lms.webservice.message.lcms.client.LMSServices.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.100.250/LCMSServer/LMSWebService/LMSServices.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.100.250/LCMSServer/LMSWebService/LMSServices.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LMSSERVICES_WSDL_LOCATION = url;
    }

    public LMSServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LMSServices() {
        super(LMSSERVICES_WSDL_LOCATION, new QName("http://360training.com/", "LMSServices"));
    }

    /**
     * 
     * @return
     *     returns LMSServicesSoap
     */
    @WebEndpoint(name = "LMSServicesSoap")
    public LMSServicesSoap getLMSServicesSoap() {
        return super.getPort(new QName("http://360training.com/", "LMSServicesSoap"), LMSServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LMSServicesSoap
     */
    @WebEndpoint(name = "LMSServicesSoap")
    public LMSServicesSoap getLMSServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://360training.com/", "LMSServicesSoap"), LMSServicesSoap.class, features);
    }

}
